//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Kaynak kodu Microsoft.VSDesigner tarafından otomatik üretilmiş , Sürüm 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace RateListing.Ui.com.message34.webservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EmailDeliverySoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Base_Result))]
    public partial class EmailDelivery : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DeliveryBulkEmailNewListXML_WithSpecialOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeliveryTransactionalEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeliveryTransactionalEmail_WithSpecialOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeliveryBulkEmailNewListOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeliveryBulkEmailNewList_WithArrayOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeliveryBulkEmailNewList_WithSpecialOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeliveryBulkEmailSegmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeliveryEmail_BasketRecoveryOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EmailDelivery() {
            this.Url = global::RateListing.Ui.Properties.Settings.Default.RateListing_Ui_com_message34_webservice_EmailDelivery;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DeliveryBulkEmailNewListXML_WithSpecialCompletedEventHandler DeliveryBulkEmailNewListXML_WithSpecialCompleted;
        
        /// <remarks/>
        public event DeliveryTransactionalEmailCompletedEventHandler DeliveryTransactionalEmailCompleted;
        
        /// <remarks/>
        public event DeliveryTransactionalEmail_WithSpecialCompletedEventHandler DeliveryTransactionalEmail_WithSpecialCompleted;
        
        /// <remarks/>
        public event DeliveryBulkEmailNewListCompletedEventHandler DeliveryBulkEmailNewListCompleted;
        
        /// <remarks/>
        public event DeliveryBulkEmailNewList_WithArrayCompletedEventHandler DeliveryBulkEmailNewList_WithArrayCompleted;
        
        /// <remarks/>
        public event DeliveryBulkEmailNewList_WithSpecialCompletedEventHandler DeliveryBulkEmailNewList_WithSpecialCompleted;
        
        /// <remarks/>
        public event DeliveryBulkEmailSegmentCompletedEventHandler DeliveryBulkEmailSegmentCompleted;
        
        /// <remarks/>
        public event DeliveryEmail_BasketRecoveryCompletedEventHandler DeliveryEmail_BasketRecoveryCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeliveryBulkEmailNewListXML_WithSpecial", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DeliveryResult DeliveryBulkEmailNewListXML_WithSpecial(string AccessToken, string FromName, string FromAddress, string Replyto, string Subject, string Body, string xmlData) {
            object[] results = this.Invoke("DeliveryBulkEmailNewListXML_WithSpecial", new object[] {
                        AccessToken,
                        FromName,
                        FromAddress,
                        Replyto,
                        Subject,
                        Body,
                        xmlData});
            return ((DeliveryResult)(results[0]));
        }
        
        /// <remarks/>
        public void DeliveryBulkEmailNewListXML_WithSpecialAsync(string AccessToken, string FromName, string FromAddress, string Replyto, string Subject, string Body, string xmlData) {
            this.DeliveryBulkEmailNewListXML_WithSpecialAsync(AccessToken, FromName, FromAddress, Replyto, Subject, Body, xmlData, null);
        }
        
        /// <remarks/>
        public void DeliveryBulkEmailNewListXML_WithSpecialAsync(string AccessToken, string FromName, string FromAddress, string Replyto, string Subject, string Body, string xmlData, object userState) {
            if ((this.DeliveryBulkEmailNewListXML_WithSpecialOperationCompleted == null)) {
                this.DeliveryBulkEmailNewListXML_WithSpecialOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeliveryBulkEmailNewListXML_WithSpecialOperationCompleted);
            }
            this.InvokeAsync("DeliveryBulkEmailNewListXML_WithSpecial", new object[] {
                        AccessToken,
                        FromName,
                        FromAddress,
                        Replyto,
                        Subject,
                        Body,
                        xmlData}, this.DeliveryBulkEmailNewListXML_WithSpecialOperationCompleted, userState);
        }
        
        private void OnDeliveryBulkEmailNewListXML_WithSpecialOperationCompleted(object arg) {
            if ((this.DeliveryBulkEmailNewListXML_WithSpecialCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeliveryBulkEmailNewListXML_WithSpecialCompleted(this, new DeliveryBulkEmailNewListXML_WithSpecialCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeliveryTransactionalEmail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DeliveryResult DeliveryTransactionalEmail(string AccessToken, string ReplyTo, string Subject, string Body, string To) {
            object[] results = this.Invoke("DeliveryTransactionalEmail", new object[] {
                        AccessToken,
                        ReplyTo,
                        Subject,
                        Body,
                        To});
            return ((DeliveryResult)(results[0]));
        }
        
        /// <remarks/>
        public void DeliveryTransactionalEmailAsync(string AccessToken, string ReplyTo, string Subject, string Body, string To) {
            this.DeliveryTransactionalEmailAsync(AccessToken, ReplyTo, Subject, Body, To, null);
        }
        
        /// <remarks/>
        public void DeliveryTransactionalEmailAsync(string AccessToken, string ReplyTo, string Subject, string Body, string To, object userState) {
            if ((this.DeliveryTransactionalEmailOperationCompleted == null)) {
                this.DeliveryTransactionalEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeliveryTransactionalEmailOperationCompleted);
            }
            this.InvokeAsync("DeliveryTransactionalEmail", new object[] {
                        AccessToken,
                        ReplyTo,
                        Subject,
                        Body,
                        To}, this.DeliveryTransactionalEmailOperationCompleted, userState);
        }
        
        private void OnDeliveryTransactionalEmailOperationCompleted(object arg) {
            if ((this.DeliveryTransactionalEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeliveryTransactionalEmailCompleted(this, new DeliveryTransactionalEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeliveryTransactionalEmail_WithSpecial", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DeliveryResult_Tran DeliveryTransactionalEmail_WithSpecial(string AccessToken, string FromName, string FromAddress, string ReplyTo, string Subject, string Body, string To) {
            object[] results = this.Invoke("DeliveryTransactionalEmail_WithSpecial", new object[] {
                        AccessToken,
                        FromName,
                        FromAddress,
                        ReplyTo,
                        Subject,
                        Body,
                        To});
            return ((DeliveryResult_Tran)(results[0]));
        }
        
        /// <remarks/>
        public void DeliveryTransactionalEmail_WithSpecialAsync(string AccessToken, string FromName, string FromAddress, string ReplyTo, string Subject, string Body, string To) {
            this.DeliveryTransactionalEmail_WithSpecialAsync(AccessToken, FromName, FromAddress, ReplyTo, Subject, Body, To, null);
        }
        
        /// <remarks/>
        public void DeliveryTransactionalEmail_WithSpecialAsync(string AccessToken, string FromName, string FromAddress, string ReplyTo, string Subject, string Body, string To, object userState) {
            if ((this.DeliveryTransactionalEmail_WithSpecialOperationCompleted == null)) {
                this.DeliveryTransactionalEmail_WithSpecialOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeliveryTransactionalEmail_WithSpecialOperationCompleted);
            }
            this.InvokeAsync("DeliveryTransactionalEmail_WithSpecial", new object[] {
                        AccessToken,
                        FromName,
                        FromAddress,
                        ReplyTo,
                        Subject,
                        Body,
                        To}, this.DeliveryTransactionalEmail_WithSpecialOperationCompleted, userState);
        }
        
        private void OnDeliveryTransactionalEmail_WithSpecialOperationCompleted(object arg) {
            if ((this.DeliveryTransactionalEmail_WithSpecialCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeliveryTransactionalEmail_WithSpecialCompleted(this, new DeliveryTransactionalEmail_WithSpecialCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeliveryBulkEmailNewList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DeliveryResult DeliveryBulkEmailNewList(string AccessToken, string Subject, string Body, System.Data.DataTable EmailList) {
            object[] results = this.Invoke("DeliveryBulkEmailNewList", new object[] {
                        AccessToken,
                        Subject,
                        Body,
                        EmailList});
            return ((DeliveryResult)(results[0]));
        }
        
        /// <remarks/>
        public void DeliveryBulkEmailNewListAsync(string AccessToken, string Subject, string Body, System.Data.DataTable EmailList) {
            this.DeliveryBulkEmailNewListAsync(AccessToken, Subject, Body, EmailList, null);
        }
        
        /// <remarks/>
        public void DeliveryBulkEmailNewListAsync(string AccessToken, string Subject, string Body, System.Data.DataTable EmailList, object userState) {
            if ((this.DeliveryBulkEmailNewListOperationCompleted == null)) {
                this.DeliveryBulkEmailNewListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeliveryBulkEmailNewListOperationCompleted);
            }
            this.InvokeAsync("DeliveryBulkEmailNewList", new object[] {
                        AccessToken,
                        Subject,
                        Body,
                        EmailList}, this.DeliveryBulkEmailNewListOperationCompleted, userState);
        }
        
        private void OnDeliveryBulkEmailNewListOperationCompleted(object arg) {
            if ((this.DeliveryBulkEmailNewListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeliveryBulkEmailNewListCompleted(this, new DeliveryBulkEmailNewListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeliveryBulkEmailNewList_WithArray", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DeliveryResult DeliveryBulkEmailNewList_WithArray(string AccessToken, string Subject, string Body, string[] EmailList_Array) {
            object[] results = this.Invoke("DeliveryBulkEmailNewList_WithArray", new object[] {
                        AccessToken,
                        Subject,
                        Body,
                        EmailList_Array});
            return ((DeliveryResult)(results[0]));
        }
        
        /// <remarks/>
        public void DeliveryBulkEmailNewList_WithArrayAsync(string AccessToken, string Subject, string Body, string[] EmailList_Array) {
            this.DeliveryBulkEmailNewList_WithArrayAsync(AccessToken, Subject, Body, EmailList_Array, null);
        }
        
        /// <remarks/>
        public void DeliveryBulkEmailNewList_WithArrayAsync(string AccessToken, string Subject, string Body, string[] EmailList_Array, object userState) {
            if ((this.DeliveryBulkEmailNewList_WithArrayOperationCompleted == null)) {
                this.DeliveryBulkEmailNewList_WithArrayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeliveryBulkEmailNewList_WithArrayOperationCompleted);
            }
            this.InvokeAsync("DeliveryBulkEmailNewList_WithArray", new object[] {
                        AccessToken,
                        Subject,
                        Body,
                        EmailList_Array}, this.DeliveryBulkEmailNewList_WithArrayOperationCompleted, userState);
        }
        
        private void OnDeliveryBulkEmailNewList_WithArrayOperationCompleted(object arg) {
            if ((this.DeliveryBulkEmailNewList_WithArrayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeliveryBulkEmailNewList_WithArrayCompleted(this, new DeliveryBulkEmailNewList_WithArrayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeliveryBulkEmailNewList_WithSpecial", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DeliveryResult DeliveryBulkEmailNewList_WithSpecial(string AccessToken, string FromName, string FromAddress, string Replyto, string Subject, string Body, System.Data.DataTable DataList) {
            object[] results = this.Invoke("DeliveryBulkEmailNewList_WithSpecial", new object[] {
                        AccessToken,
                        FromName,
                        FromAddress,
                        Replyto,
                        Subject,
                        Body,
                        DataList});
            return ((DeliveryResult)(results[0]));
        }
        
        /// <remarks/>
        public void DeliveryBulkEmailNewList_WithSpecialAsync(string AccessToken, string FromName, string FromAddress, string Replyto, string Subject, string Body, System.Data.DataTable DataList) {
            this.DeliveryBulkEmailNewList_WithSpecialAsync(AccessToken, FromName, FromAddress, Replyto, Subject, Body, DataList, null);
        }
        
        /// <remarks/>
        public void DeliveryBulkEmailNewList_WithSpecialAsync(string AccessToken, string FromName, string FromAddress, string Replyto, string Subject, string Body, System.Data.DataTable DataList, object userState) {
            if ((this.DeliveryBulkEmailNewList_WithSpecialOperationCompleted == null)) {
                this.DeliveryBulkEmailNewList_WithSpecialOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeliveryBulkEmailNewList_WithSpecialOperationCompleted);
            }
            this.InvokeAsync("DeliveryBulkEmailNewList_WithSpecial", new object[] {
                        AccessToken,
                        FromName,
                        FromAddress,
                        Replyto,
                        Subject,
                        Body,
                        DataList}, this.DeliveryBulkEmailNewList_WithSpecialOperationCompleted, userState);
        }
        
        private void OnDeliveryBulkEmailNewList_WithSpecialOperationCompleted(object arg) {
            if ((this.DeliveryBulkEmailNewList_WithSpecialCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeliveryBulkEmailNewList_WithSpecialCompleted(this, new DeliveryBulkEmailNewList_WithSpecialCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeliveryBulkEmailSegment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DeliveryResult DeliveryBulkEmailSegment(string AccessToken, string Subject, string Body, string Condition) {
            object[] results = this.Invoke("DeliveryBulkEmailSegment", new object[] {
                        AccessToken,
                        Subject,
                        Body,
                        Condition});
            return ((DeliveryResult)(results[0]));
        }
        
        /// <remarks/>
        public void DeliveryBulkEmailSegmentAsync(string AccessToken, string Subject, string Body, string Condition) {
            this.DeliveryBulkEmailSegmentAsync(AccessToken, Subject, Body, Condition, null);
        }
        
        /// <remarks/>
        public void DeliveryBulkEmailSegmentAsync(string AccessToken, string Subject, string Body, string Condition, object userState) {
            if ((this.DeliveryBulkEmailSegmentOperationCompleted == null)) {
                this.DeliveryBulkEmailSegmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeliveryBulkEmailSegmentOperationCompleted);
            }
            this.InvokeAsync("DeliveryBulkEmailSegment", new object[] {
                        AccessToken,
                        Subject,
                        Body,
                        Condition}, this.DeliveryBulkEmailSegmentOperationCompleted, userState);
        }
        
        private void OnDeliveryBulkEmailSegmentOperationCompleted(object arg) {
            if ((this.DeliveryBulkEmailSegmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeliveryBulkEmailSegmentCompleted(this, new DeliveryBulkEmailSegmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeliveryEmail_BasketRecovery", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DeliveryResult DeliveryEmail_BasketRecovery(string AccessToken, string FromName, string FromAddress, string ReplyTo, string Subject, string Body, System.Data.DataTable BasketData, System.DateTime SendDate, int Type) {
            object[] results = this.Invoke("DeliveryEmail_BasketRecovery", new object[] {
                        AccessToken,
                        FromName,
                        FromAddress,
                        ReplyTo,
                        Subject,
                        Body,
                        BasketData,
                        SendDate,
                        Type});
            return ((DeliveryResult)(results[0]));
        }
        
        /// <remarks/>
        public void DeliveryEmail_BasketRecoveryAsync(string AccessToken, string FromName, string FromAddress, string ReplyTo, string Subject, string Body, System.Data.DataTable BasketData, System.DateTime SendDate, int Type) {
            this.DeliveryEmail_BasketRecoveryAsync(AccessToken, FromName, FromAddress, ReplyTo, Subject, Body, BasketData, SendDate, Type, null);
        }
        
        /// <remarks/>
        public void DeliveryEmail_BasketRecoveryAsync(string AccessToken, string FromName, string FromAddress, string ReplyTo, string Subject, string Body, System.Data.DataTable BasketData, System.DateTime SendDate, int Type, object userState) {
            if ((this.DeliveryEmail_BasketRecoveryOperationCompleted == null)) {
                this.DeliveryEmail_BasketRecoveryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeliveryEmail_BasketRecoveryOperationCompleted);
            }
            this.InvokeAsync("DeliveryEmail_BasketRecovery", new object[] {
                        AccessToken,
                        FromName,
                        FromAddress,
                        ReplyTo,
                        Subject,
                        Body,
                        BasketData,
                        SendDate,
                        Type}, this.DeliveryEmail_BasketRecoveryOperationCompleted, userState);
        }
        
        private void OnDeliveryEmail_BasketRecoveryOperationCompleted(object arg) {
            if ((this.DeliveryEmail_BasketRecoveryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeliveryEmail_BasketRecoveryCompleted(this, new DeliveryEmail_BasketRecoveryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DeliveryResult : Base_Result {
        
        private int deliveryCountField;
        
        private string campaignId_UniqueField;
        
        /// <remarks/>
        public int DeliveryCount {
            get {
                return this.deliveryCountField;
            }
            set {
                this.deliveryCountField = value;
            }
        }
        
        /// <remarks/>
        public string CampaignId_Unique {
            get {
                return this.campaignId_UniqueField;
            }
            set {
                this.campaignId_UniqueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeliveryResult_Tran))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeliveryResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Base_Result {
        
        private bool statusField;
        
        private string descriptionField;
        
        private ResultDesc resultCodeField;
        
        /// <remarks/>
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public ResultDesc ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum ResultDesc {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        TokenError,
        
        /// <remarks/>
        DataBaseError,
        
        /// <remarks/>
        SystemError,
        
        /// <remarks/>
        DeliveryError,
        
        /// <remarks/>
        NoData,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DeliveryResult_Tran : Base_Result {
        
        private int deliveryCountField;
        
        private string campaignIdTran_UniqueField;
        
        /// <remarks/>
        public int DeliveryCount {
            get {
                return this.deliveryCountField;
            }
            set {
                this.deliveryCountField = value;
            }
        }
        
        /// <remarks/>
        public string CampaignIdTran_Unique {
            get {
                return this.campaignIdTran_UniqueField;
            }
            set {
                this.campaignIdTran_UniqueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DeliveryBulkEmailNewListXML_WithSpecialCompletedEventHandler(object sender, DeliveryBulkEmailNewListXML_WithSpecialCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeliveryBulkEmailNewListXML_WithSpecialCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeliveryBulkEmailNewListXML_WithSpecialCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeliveryResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeliveryResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DeliveryTransactionalEmailCompletedEventHandler(object sender, DeliveryTransactionalEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeliveryTransactionalEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeliveryTransactionalEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeliveryResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeliveryResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DeliveryTransactionalEmail_WithSpecialCompletedEventHandler(object sender, DeliveryTransactionalEmail_WithSpecialCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeliveryTransactionalEmail_WithSpecialCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeliveryTransactionalEmail_WithSpecialCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeliveryResult_Tran Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeliveryResult_Tran)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DeliveryBulkEmailNewListCompletedEventHandler(object sender, DeliveryBulkEmailNewListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeliveryBulkEmailNewListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeliveryBulkEmailNewListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeliveryResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeliveryResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DeliveryBulkEmailNewList_WithArrayCompletedEventHandler(object sender, DeliveryBulkEmailNewList_WithArrayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeliveryBulkEmailNewList_WithArrayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeliveryBulkEmailNewList_WithArrayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeliveryResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeliveryResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DeliveryBulkEmailNewList_WithSpecialCompletedEventHandler(object sender, DeliveryBulkEmailNewList_WithSpecialCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeliveryBulkEmailNewList_WithSpecialCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeliveryBulkEmailNewList_WithSpecialCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeliveryResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeliveryResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DeliveryBulkEmailSegmentCompletedEventHandler(object sender, DeliveryBulkEmailSegmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeliveryBulkEmailSegmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeliveryBulkEmailSegmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeliveryResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeliveryResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DeliveryEmail_BasketRecoveryCompletedEventHandler(object sender, DeliveryEmail_BasketRecoveryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeliveryEmail_BasketRecoveryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeliveryEmail_BasketRecoveryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DeliveryResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DeliveryResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591